services:
  collector:
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - ./otel-config.yaml:/etc/otelcol-contrib/config.yaml
    command: ["--config=/etc/otelcol-contrib/config.yaml"]
    ports:
      - "4317:4317"
  zenoh-logger:
    build: .
    #network_mode: "host"
    command: python main.py --query ${ZENOH_TOPIC_QUERY} --collector ${COLLECTOR_URL}
    volumes:
      - .:/usr/src/app
      - ./zenohd_config.json5:/config/zenoh_config.json5:ro
      - ./zenoh_client.crt:/config/zenoh_client.crt:ro
      - ./zenoh_client.key:/config/zenoh_client.key:ro
      - ./zenoh_rootca.crt:/config/zenoh_rootca.crt:ro

